const cells=[...document.querySelectorAll('.cell')],statusText=document.querySelector('#status-text'),roundEl=document.querySelector('#round-number'),selectors=document.querySelector('#player-selectors'),p1=document.querySelector('#player-one-select'),p2=document.querySelector('#player-two-select');
const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]],names=['Top left','Top center','Top right','Middle left','Center','Middle right','Bottom left','Bottom center','Bottom right'];let board=Array(9).fill(''),current='X',over=false,mode='single',round=1,players=JSON.parse(localStorage.getItem('neon-grid-players')||'[]');
function render(){document.querySelector('#leaderboard').innerHTML=players.length?players.sort((a,b)=>b.score-a.score).map(p=>`<li><span>${p.name}</span><span class="player-score">${p.score}</span></li>`).join(''):'<li class="empty">No players registered yet.</li>';const opts=players.length?players.map(p=>`<option>${p.name}</option>`).join(''):'<option>Register players first</option>';p1.innerHTML=opts;p2.innerHTML=opts;if(players.length>1)p2.selectedIndex=1}
function pname(mark){return mode==='multi'?(mark==='X'?p1.value:p2.value):(mark==='X'?(document.querySelector('#player-name').value.trim()||'You'):'System')}
function reset(){board=Array(9).fill('');current='X';over=false;roundEl.textContent=String(round).padStart(2,'0');cells.forEach((c,i)=>{c.textContent='';c.disabled=false;c.className='cell';c.setAttribute('aria-label',names[i]+', empty')});statusText.textContent=`${pname('X')} · X's turn`}
function finish(w,line=[]){over=true;line.forEach(i=>cells[i].classList.add('win'));if(w==='draw')return statusText.textContent='Draw · well played';const n=pname(w);statusText.textContent=`${n} · ${w} wins`;const p=players.find(x=>x.name===n);if(p)p.score++;localStorage.setItem('neon-grid-players',JSON.stringify(players));render()}
function move(i){if(over||board[i])return;board[i]=current;const c=cells[i];c.textContent=current==='X'?'×':'○';c.classList.add(current.toLowerCase());c.disabled=true;c.setAttribute('aria-label',`${names[i]}, ${current}`);const line=wins.find(x=>x.every(n=>board[n]===current));if(line)return finish(current,line);if(board.every(Boolean))return finish('draw');current=current==='X'?'O':'X';statusText.textContent=`${pname(current)} · ${current}'s turn`;if(mode==='single'&&current==='O')setTimeout(ai,400)}
function ai(){const empty=board.map((v,i)=>v?null:i).filter(i=>i!==null);let i=empty.find(x=>{board[x]='O';const ok=wins.some(w=>w.every(n=>board[n]==='O'));board[x]='';return ok});if(i===undefined)i=empty.find(x=>{board[x]='X';const ok=wins.some(w=>w.every(n=>board[n]==='X'));board[x]='';return ok});if(i===undefined)i=empty.includes(4)?4:empty[Math.floor(Math.random()*empty.length)];move(i)}
cells.forEach(c=>c.addEventListener('click',()=>move(+c.dataset.index)));document.querySelector('#new-round').onclick=()=>{round++;reset()};document.querySelector('#reset-score').onclick=()=>{players=players.map(p=>({...p,score:0}));localStorage.setItem('neon-grid-players',JSON.stringify(players));render()};document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;selectors.hidden=mode!=='multi';round=1;reset()});[p1,p2].forEach(s=>s.onchange=reset);document.querySelector('#signup-form').onsubmit=e=>{e.preventDefault();const input=document.querySelector('#player-name'),n=input.value.trim(),msg=document.querySelector('#form-message');if(!n)return msg.textContent='Please enter a name to join.';if(players.some(p=>p.name.toLowerCase()===n.toLowerCase()))return msg.textContent='That player is already registered.';players.push({name:n,score:0});localStorage.setItem('neon-grid-players',JSON.stringify(players));render();msg.textContent=`${n} joined the grid.`;input.value=''};render();reset();
